### ISSUE TITLE
Exception reported by Michiel

### ISSUE THREAD

**Issue by hangal** [ePADD/epadd#125]
Probably happens in the special case of the name being just a single single- or double-quote.

> at com.sun.mail.imap.IMAPStore.protocolConnect(IMAPStore.java:606)
> at javax.mail.Service.connect(Service.java:291)
> at edu.stanford.muse.email.ImapPopEmailStore.connect(ImapPopEmailStore.java:263)
> at edu.stanford.muse.email.MuseEmailFetcher.doConnect(MuseEmailFetcher.java:272)
> at edu.stanford.muse.email.MuseEmailFetcher.addServerAccount(MuseEmailFetcher.java:244)
> at edu.stanford.muse.webapp.Accounts.login(Accounts.java:204)
> at org.apache.jsp.ajax.doLogin_jsp._jspService(doLogin_jsp.java:141)
> at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
> at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
> at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:438)
> at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:396)
> at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:340)
> at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
> at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
> at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
> at edu.stanford.muse.webapp.LoggingFilter.doFilter(LoggingFilter.java:26)
> at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
> at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
> at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
> at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
> at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)

**Comment by hangal** [comment]
Michiel reports that this bug has been fixed, per email received week of June 5. Hence closing.
