### ISSUE TITLE
Migration 

### ISSUE THREAD

**Issue by peterchanws** [ePADD/epadd#187]
User found 
1. message in v4 missing in v5 
2. "While the second search did show up in V5, but did not have the annotation transferred (though the transfer with restrictions label did remain): " 
3. total no of "transfer with restriction" messages in v4 and v5 is different.

I have send you the relevant emails.

**Comment by chinuhub** [comment]
@peterchanws  Can you please ask them to send me the annotations.csv file? This file gets generated during exporting the v4 archive to v5.

**Comment by peterchanws** [comment]
I got the files from users and run them under v4 & 5. Results are as follows:

Version 5 
without specify email address of email owner: 79568 incoming
specify ian.mcewan@mac.com as  email address of email owner: 52259 incoming, 27309 outgoing 
Result got from UT: 51341 incoming, 26125 outgoing (total 77466)

Version 4

![mcewan-v5-1](https://user-images.githubusercontent.com/1050899/37924773-b7beb22a-30e7-11e8-8033-fc758a4b14fd.PNG)
![mcewan-v5-2](https://user-images.githubusercontent.com/1050899/37924780-bdfb4c3e-30e7-11e8-99a8-aa4371027ac1.PNG)
![ian mcewan mac com-v5-3](https://user-images.githubusercontent.com/1050899/37924787-c110aee6-30e7-11e8-8410-5f48ced958d8.PNG)
![epadd-emails-v5](https://user-images.githubusercontent.com/1050899/37924794-c5ca92c6-30e7-11e8-9a46-275a09844e3e.png)

**Comment by peterchanws** [comment]
Reid: I've completed the migration assistant, copied over the address book, and replaced the files. The incoming/outgoing all match up now. In the Export Screen for V4 I see 838 restricted messages, vs. 835 in V5's Labels screen. So close! 

What's the next step?

**Comment by peterchanws** [comment]
v4: all 79568 messages are annotated and labelled as  transfer with restriction label

v5:
78500  transfer with restriction label 1068 without the label
1068 not annotated

**Comment by hangal** [comment]
We think we have a clue -- it may be due to the encoding on the machine.
Can you clarify which machines you did the v4 and v5 import on?

**Comment by peterchanws** [comment]
v4 in Mac and v5 in WIndows

**Comment by hangal** [comment]
ah, that may be the rub.
It's possible that the default encoding is different on these 2, and
therefore the messages are not being found in v5.
We'll give you a fix to fix the encoding.

**Comment by peterchanws** [comment]
I used the same Windows machine for v4 and v5 and got the following in v5
Annotated (79266)
Not annotated (302)

So, default encoding account for 1068-302 messages

**Comment by peterchanws** [comment]
Using v5 and v4-export uploaded 04/13/2018, I got the following result:

Annotations
Annotated (79266)
Not annotated (302)

**Comment by peterchanws** [comment]
Using same Windows machine for v4 and v5, I have all messages transferred properly.

**Comment by hangal** [comment]
Just to clarify: 
When you write Win 10 home -> win 10 home, is it actually the same machine, or a different one?

Also, btw, one thing to check in the log is the file.encoding system property, which is printed near the top.

**Comment by peterchanws** [comment]
Microsoft Windows [Version 10.0.16299.371]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\Users\peter>java -Xmx16g -jar epadd-standalone.v54.jar
ePADD properties file C:\Users\peter\epadd.properties does not exist or is not readable
splash url = jar:file:/C:/Users/peter/epadd-standalone.v54.jar!/splash-image.png w=795.0 h=285.0 size=java.awt.Dimension[width=795,height=285] loc=java.awt.Point[x=562,y=397]
Setting up logging...
Set logging to C:\Users\peter\epadd-settings\epadd.log
Apr 16, 2018 9:02:24 PM org.apache.catalina.core.StandardContext setPath
WARNING: A context path must either be an empty string or start with a '/' and do not end with a '/'. The path [/] does not meet these criteria and has been changed to []
Apr 16, 2018 9:02:28 PM org.apache.coyote.AbstractProtocol init
INFO: Initializing ProtocolHandler ["http-nio-9099"]
Apr 16, 2018 9:02:29 PM org.apache.tomcat.util.net.NioSelectorPool getSharedSelector
INFO: Using a shared selector for servlet write/read
Apr 16, 2018 9:02:29 PM org.apache.catalina.core.StandardService startInternal
INFO: Starting service Tomcat
Apr 16, 2018 9:02:29 PM org.apache.catalina.core.StandardEngine startInternal
INFO: Starting Servlet Engine: Apache Tomcat/8.0.29
Apr 16, 2018 9:02:30 PM org.apache.catalina.startup.ContextConfig getDefaultWebXmlFragment
INFO: No global web.xml found
Apr 16, 2018 9:02:31 PM org.apache.jasper.servlet.TldScanner scanJars
INFO: At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
Apr 16, 2018 9:02:32 PM org.apache.catalina.startup.ContextConfig beforeStart
SEVERE: Exception fixing docBase for context [/epadd]
java.util.zip.ZipException: invalid LOC header (bad signature)
        at java.util.zip.ZipFile.read(Native Method)
        at java.util.zip.ZipFile.access$1400(Unknown Source)
        at java.util.zip.ZipFile$ZipFileInputStream.read(Unknown Source)
        at java.util.zip.ZipFile$ZipFileInflaterInputStream.fill(Unknown Source)
        at java.util.zip.InflaterInputStream.read(Unknown Source)
        at java.io.FilterInputStream.read(Unknown Source)
        at org.apache.catalina.startup.ExpandWar.expand(ExpandWar.java:381)
        at org.apache.catalina.startup.ExpandWar.expand(ExpandWar.java:165)
        at org.apache.catalina.startup.ContextConfig.fixDocBase(ContextConfig.java:618)
        at org.apache.catalina.startup.ContextConfig.beforeStart(ContextConfig.java:744)
        at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:307)
        at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:95)
        at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:90)
        at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:402)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1408)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1398)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

Apr 16, 2018 9:02:32 PM org.apache.catalina.core.ContainerBase startInternal
SEVERE: A child container failed during start
java.util.concurrent.ExecutionException: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Tomcat].StandardHost[localhost].StandardContext[/epadd]]
        at java.util.concurrent.FutureTask.report(Unknown Source)
        at java.util.concurrent.FutureTask.get(Unknown Source)
        at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:916)
        at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:871)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1408)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1398)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Tomcat].StandardHost[localhost].StandardContext[/epadd]]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:154)
        ... 6 more
Caused by: org.apache.catalina.LifecycleException: Failed to start component [org.apache.catalina.webresources.StandardRoot@1eab9c2c]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:154)
        at org.apache.catalina.core.StandardContext.resourcesStart(StandardContext.java:4909)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5039)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        ... 6 more
Caused by: org.apache.catalina.LifecycleException: Failed to initialize component [org.apache.catalina.webresources.JarWarResourceSet@1400e3ef]
        at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:106)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:139)
        at org.apache.catalina.webresources.StandardRoot.startInternal(StandardRoot.java:699)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        ... 9 more
Caused by: java.lang.IllegalArgumentException: java.util.zip.ZipException: invalid LOC header (bad signature)
        at org.apache.catalina.webresources.JarWarResourceSet.initInternal(JarWarResourceSet.java:104)
        at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:102)
        ... 12 more
Caused by: java.util.zip.ZipException: invalid LOC header (bad signature)
        at java.util.zip.ZipFile.read(Native Method)
        at java.util.zip.ZipFile.access$1400(Unknown Source)
        at java.util.zip.ZipFile$ZipFileInputStream.read(Unknown Source)
        at java.io.FilterInputStream.read(Unknown Source)
        at java.io.PushbackInputStream.read(Unknown Source)
        at java.util.zip.ZipInputStream.readFully(Unknown Source)
        at java.util.zip.ZipInputStream.readLOC(Unknown Source)
        at java.util.zip.ZipInputStream.getNextEntry(Unknown Source)
        at java.util.jar.JarInputStream.<init>(Unknown Source)
        at java.util.jar.JarInputStream.<init>(Unknown Source)
        at org.apache.catalina.webresources.JarWarResourceSet.initInternal(JarWarResourceSet.java:95)
        ... 13 more

Apr 16, 2018 9:02:32 PM org.apache.catalina.core.ContainerBase startInternal
SEVERE: A child container failed during start
java.util.concurrent.ExecutionException: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Tomcat].StandardHost[localhost]]
        at java.util.concurrent.FutureTask.report(Unknown Source)
        at java.util.concurrent.FutureTask.get(Unknown Source)
        at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:916)
        at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:262)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.StandardService.startInternal(StandardService.java:439)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:769)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.startup.Tomcat.start(Tomcat.java:344)
        at edu.stanford.epadd.launcher.TomcatMain.main(TomcatMain.java:826)
Caused by: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Tomcat].StandardHost[localhost]]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:154)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1408)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1398)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: org.apache.catalina.LifecycleException: A child container failed during start
        at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:924)
        at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:871)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        ... 6 more

Exception in thread "main" org.apache.catalina.LifecycleException: Failed to start component [StandardServer[-1]]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:154)
        at org.apache.catalina.startup.Tomcat.start(Tomcat.java:344)
        at edu.stanford.epadd.launcher.TomcatMain.main(TomcatMain.java:826)
Caused by: org.apache.catalina.LifecycleException: Failed to start component [StandardService[Tomcat]]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:154)
        at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:769)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        ... 2 more
Caused by: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Tomcat]]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:154)
        at org.apache.catalina.core.StandardService.startInternal(StandardService.java:439)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        ... 4 more
Caused by: org.apache.catalina.LifecycleException: A child container failed during start
        at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:924)
        at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:262)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        ... 6 more

C:\Users\peter>

**Comment by peterchanws** [comment]
epadd version April 16
Machine with Windows Home edition
file.encoding=Cp1252
total message=70206

**Comment by peterchanws** [comment]
labels from 79562 out of 79568 messages migrated to v5

**Comment by peterchanws** [comment]
UT has successfully migrated to v5.
