### ISSUE TITLE
28July v6 version failed to start

### ISSUE THREAD

**Issue by peterchanws** [ePADD/epadd#258]
@chinuhub epadd-settings exist in home folder. Here is what terminal show:

li-bd-6339-25b5:~ pchan3$ java -Xmx16g -jar epadd-standalone-v6-beta2-28July.jar 
Reading configuration from: /Users/pchan3/epadd.properties
splash url = jar:file:/Users/pchan3/epadd-standalone-v6-beta2-28July.jar!/splash-image.png w=795.0 h=285.0 size=java.awt.Dimension[width=795,height=285] loc=java.awt.Point[x=322,y=307]
Setting up logging...
Set logging to /Users/pchan3/epadd-settings/epadd.log
Starting up ePADD on the local computer at http://localhost:9099/epadd/, 2018-07-28 08:05:30
Sorry! Unable to locate epadd-settings on classpath: 
Jul 28, 2018 8:05:31 AM org.apache.coyote.AbstractProtocol init
INFO: Initializing ProtocolHandler ["http-nio-9099"]
Jul 28, 2018 8:05:31 AM org.apache.tomcat.util.net.NioSelectorPool getSharedSelector
INFO: Using a shared selector for servlet write/read
Jul 28, 2018 8:05:31 AM org.apache.catalina.core.StandardService startInternal
INFO: Starting service Tomcat
Exception in thread "main" org.apache.catalina.LifecycleException: Failed to start component [StandardServer[-1]]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:154)
	at org.apache.catalina.startup.Tomcat.start(Tomcat.java:344)
	at edu.stanford.epadd.launcher.TomcatMain.main(TomcatMain.java:954)
Caused by: org.apache.catalina.LifecycleException: Failed to start component [StandardService[Tomcat]]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:154)
	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:769)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	... 2 more
Caused by: org.apache.catalina.LifecycleException: Failed to start component [org.apache.catalina.mapper.MapperListener@3ffc5af1]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:154)
	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:450)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	... 4 more
Caused by: java.lang.NullPointerException
	at org.apache.catalina.mapper.MapperListener.findDefaultHost(MapperListener.java:259)
	at org.apache.catalina.mapper.MapperListener.startInternal(MapperListener.java:100)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	... 6 more
li-bd-6339-25b5:~ pchan3$ java -Xmx16g -jar epadd-standalone-v6-beta2-28July.jar
Reading configuration from: /Users/pchan3/epadd.properties
splash url = jar:file:/Users/pchan3/epadd-standalone-v6-beta2-28July.jar!/splash-image.png w=795.0 h=285.0 size=java.awt.Dimension[width=795,height=285] loc=java.awt.Point[x=322,y=307]
Setting up logging...
Set logging to /Users/pchan3/epadd-settings/epadd.log
Starting up ePADD on the local computer at http://localhost:9099/epadd/, 2018-07-28 08:06:29
Sorry! Unable to locate epadd-settings on classpath: 
Jul 28, 2018 8:06:29 AM org.apache.coyote.AbstractProtocol init
INFO: Initializing ProtocolHandler ["http-nio-9099"]
Jul 28, 2018 8:06:29 AM org.apache.tomcat.util.net.NioSelectorPool getSharedSelector
INFO: Using a shared selector for servlet write/read
Jul 28, 2018 8:06:29 AM org.apache.catalina.core.StandardService startInternal
INFO: Starting service Tomcat
Exception in thread "main" org.apache.catalina.LifecycleException: Failed to start component [StandardServer[-1]]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:154)
	at org.apache.catalina.startup.Tomcat.start(Tomcat.java:344)
	at edu.stanford.epadd.launcher.TomcatMain.main(TomcatMain.java:954)
Caused by: org.apache.catalina.LifecycleException: Failed to start component [StandardService[Tomcat]]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:154)
	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:769)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	... 2 more
Caused by: org.apache.catalina.LifecycleException: Failed to start component [org.apache.catalina.mapper.MapperListener@3ffc5af1]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:154)
	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:450)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	... 4 more
Caused by: java.lang.NullPointerException
	at org.apache.catalina.mapper.MapperListener.findDefaultHost(MapperListener.java:259)
	at org.apache.catalina.mapper.MapperListener.startInternal(MapperListener.java:100)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	... 6 more
li-bd-6339-25b5:~ pchan3$

**Comment by peterchanws** [comment]
Problem fixed.
