### ISSUE TITLE
epadd crash after editing entity book

### ISSUE THREAD

**Issue by SachinSalunke** [ePADD/epadd#273]
after editing entity book for companies to merge ICICI bank and ICICI Lombard, epadd stopped working and is unable to read the archive.

13 Aug 11:28:49 SimpleSessions INFO  - end of session file reached
13 Aug 11:28:49 SimpleSessions INFO  - Memory status: 938 MB free, 106 MB used, 3641 MB max, 1044 MB total
13 Aug 11:28:49 Config INFO  - Reading resource name-variants.txt from C:\Users\sachs\epadd-settings\name-variants.txt
13 Aug 11:28:50 SimpleSessions WARN  - Error reading archive from dir: C:\Users\sachs\epadd-appraisal\user\data\sessions\default.archive.v2
java.lang.NumberFormatException: For input string: "1-------------------------------------------"
java.lang.NumberFormatException: For input string: "1-------------------------------------------"
	at java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at java.lang.Short.parseShort(Unknown Source)
	at java.lang.Short.parseShort(Unknown Source)
	at edu.stanford.muse.ie.variants.MappedEntity.readObjectFromStream(MappedEntity.java:96)
	at edu.stanford.muse.ie.variants.EntityBook.readObjectFromStream(EntityBook.java:239)
	at edu.stanford.muse.index.ArchiveReaderWriter.readEntityBook(ArchiveReaderWriter.java:207)
	at edu.stanford.muse.index.ArchiveReaderWriter.loadSessionAsMap(ArchiveReaderWriter.java:154)
	at edu.stanford.muse.index.ArchiveReaderWriter.readArchiveIfPresent(ArchiveReaderWriter.java:687)
	at edu.stanford.muse.index.ArchiveReaderWriter.prepareAndLoadDefaultArchive(ArchiveReaderWriter.java:781)
	at org.apache.jsp.index_jsp._jspService(index_jsp.java:173)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:438)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:396)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:340)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at edu.stanford.muse.webapp.LoggingFilter.doFilter(LoggingFilter.java:26)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)

**Comment by chinuhub** [comment]
Can not reproduce in Koch full.

**Comment by hangal** [comment]
what if you try to close the archive and epadd, and start again?
We did see this repeatably on Peter and Sachin's laptops.

**Comment by peterchanws** [comment]
23-Aug-v6.1
Can't reproduce (even in v6)

**Comment by chinuhub** [comment]
To reproduce this issue, go to Person entity -> edit entities and then remove some barriers to combine any two names. Save the archive. Exit ePADD and open it again.

The issue was due to the improper formatting (missing new line) when writing entityBook in the session folder. The generated format was

###Names###David
###EntityType###
0-------------------------------------------

Whereas the expected format was
###Names###
David
###EntityType###
0
-------------------------------------------

In this fix we correct the writing and reading format for entityBook. But because of the change in the writing format, the entityBook file (if non-empty) generated from the old version of ePADD needs to be manually edited (as shown above) to correct it. This point onward, ePADD will correctly read and write it.

**Comment by peterchanws** [comment]
ver 6.1 sep 6
fixed
