### ISSUE TITLE
 UNABLE TO READ RESOURCE FILE: kill.txt: Indexing stopped, 

### ISSUE THREAD

**Issue by peterchanws** [ePADD/epadd#344]
ver 7 Jan 11; Win 10; 16GB RAM Terry+Bush+Fikes

Indexing started at~22:00 Jan 11, process stooped at  
12 Jan 16:56:10 Config WARN  - UNABLE TO READ RESOURCE FILE: kill.txt
Exception while reading taboo list from config file: kill.txt
java.lang.NullPointerException
        at java.io.Reader.<init>(Unknown Source)
        at java.io.InputStreamReader.<init>(Unknown Source)
        at edu.stanford.muse.ie.KillPhrases.<clinit>(KillPhrases.java:12)
        at edu.stanford.muse.ner.NER.lambda$getNames$0(NER.java:172)
        at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source)
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.util.stream.ReferencePipeline.collect(Unknown Source)
        at edu.stanford.muse.ner.NER.getNames(NER.java:172)
        at edu.stanford.muse.ner.NER.getNames(NER.java:180)
        at edu.stanford.muse.ie.variants.EntityBookManager.getEntitiesInDocFromLucene(EntityBookManager.java:326)
        at edu.stanford.muse.ie.variants.EntityBookManager.fillEntityBookFromLucene(EntityBookManager.java:347)
        at edu.stanford.muse.ie.variants.EntityBookManager.getEntityBookForType(EntityBookManager.java:51)
        at edu.stanford.muse.ie.variants.EntityBookManager.getEntitiesCountMapModuloThreshold(EntityBookManager.java:213)
        at edu.stanford.muse.webapp.JSPHelper.fetchAndIndexEmails(JSPHelper.java:423)
        at org.apache.jsp.ajax.async.doFetchAndIndex_jsp.doFetchAndIndex(doFetchAndIndex_jsp.java:99)
        at org.apache.jsp.ajax.async.doFetchAndIndex_jsp$1.onStart(doFetchAndIndex_jsp.java:331)
        at edu.stanford.epadd.util.OperationInfo.lambda$run$0(OperationInfo.java:61)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

**Comment by peterchanws** [comment]
ver 7 Jan 11; Mac; 16GB RAM Terry+Bush+Fikes
Finished indexing in 10 hrs. Quit and load indexed archive in appraisal, process stopped : command prompt show 
UNABLE TO READ RESOURCE FILE: kill.txt
Exception while reading taboo list from config file: kill.txt

**Comment by peterchanws** [comment]
ver 7 Jan 11; Mac; 16GB RAM; 4-cores; Terry+Bush+Fikes
export from appraisal - success,  import to processing - success , load archive from collection in processing - no collection at this location

Since I can index Terry+Bush+Fikes in another machine, this case is closed.
