### ISSUE TITLE
Unable to start discovery module using epadd-discovery-standalone.jar

### ISSUE THREAD

**Issue by peterchanws** [ePADD/epadd#350]
ver Jan 22
user the following command:
java -Djava.io.tmpdir=/opt/app/sulmuse/tmp -Depadd.mode.discovery=1 -Dnobrowseropen= -Xmx2g -jar epadd-discovery-standalone.jar -no-browser-open

Got the following in command prompt:

Jan 23, 2019 1:30:44 PM org.apache.coyote.AbstractProtocol init
INFO: Initializing ProtocolHandler ["http-nio-9099"]
Jan 23, 2019 1:30:44 PM org.apache.tomcat.util.net.NioSelectorPool getSharedSelector
INFO: Using a shared selector for servlet write/read
Jan 23, 2019 1:30:44 PM org.apache.catalina.core.StandardService startInternal
INFO: Starting service Tomcat
Exception in thread "main" org.apache.catalina.LifecycleException: Failed to start component [StandardServer[-1]]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:154)
	at org.apache.catalina.startup.Tomcat.start(Tomcat.java:344)
	at edu.stanford.epadd.launcher.ePADD.main(ePADD.java:966)
Caused by: org.apache.catalina.LifecycleException: Failed to start component [StandardService[Tomcat]]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:154)
	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:769)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	... 2 more
Caused by: org.apache.catalina.LifecycleException: Failed to start component [org.apache.catalina.mapper.MapperListener@57536d79]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:154)
	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:450)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	... 4 more
Caused by: java.lang.NullPointerException
	at org.apache.catalina.mapper.MapperListener.findDefaultHost(MapperListener.java:259)
	at org.apache.catalina.mapper.MapperListener.startInternal(MapperListener.java:100)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	... 6 more

**Comment by hangal** [comment]
sorry about this. I have uploaded a fresh build under the same release. please try with this.

**Comment by peterchanws** [comment]
tried in 2 different machine and still can't start

**Comment by chinuhub** [comment]
It looks like you did not have the correct tmp directory location. Try the following command;

1. First, set the property epadd.mode=discovery in epadd.settings file.
Run following command;
2. java -Djava.io.tmpdir=/tmp -Depadd.mode.discovery=1 -Dnobrowseropen= -Xmx2g -jar epadd-discovery-standalone.jar -no-browser-open

Then open localhost:9099 in your browser.

**Comment by peterchanws** [comment]
It works now. We will need to update our manual.
