### ISSUE TITLE
Exception fetching/indexing emails

### ISSUE THREAD

**Issue by peterchanws** [ePADD/epadd#365]
ver 7.1 Bush small Windows 10 Chrome

I encountered this issues in 3 Windows machines in Library of Congress and 2 Windows machines at Stanford. No problem with Mac.

Error log:

If you have encountered a problem, please provide the following details to epadd_project@stanford.edu to help us fix the problem:
Total RAM in your system
Name of the screens you went through and the input boxes filled on those screens (or screen prints). state the steps to reproduce the problem.
If the problem was encountered while importing emails then please mention the source of mbox file and the software (if any) used to convert it to mbox format.
Number of email messages and the size (in GB) of the archive.
If necessary, can you share the email files with us to find out the issue?
The log given below.
Jump to: Configuration • Session • Warnings • Log 
ePADD version Release 7.1 
Build Info: Built by tech at May 18, 2019 06:45 PM on Mac OS X 10.14 x86_64 
Browser
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36 

Memory status
1024 MB free, 50 MB used, 3641 MB max, 1074 MB total

System properties
java.runtime.name: Java(TM) SE Runtime Environment
sun.boot.library.path: C:\Program Files\Java\jre1.8.0_211\bin
java.vm.version: 25.211-b12
com.apple.mrj.application.apple.menu.about.name: ePADD
muse.defaultArchivesDir: C:\Users\Peter Chan\epadd-appraisal
java.vm.vendor: Oracle Corporation
java.vendor.url: http://java.oracle.com/
path.separator: ;
java.vm.name: Java HotSpot(TM) 64-Bit Server VM
file.encoding.pkg: sun.io
user.script: 
user.country: US
sun.java.launcher: SUN_STANDARD
sun.os.patch.level: 
java.vm.specification.name: Java Virtual Machine Specification
user.dir: C:\Users\Peter Chan\Desktop
java.runtime.version: 1.8.0_211-b12
java.awt.graphicsenv: sun.awt.Win32GraphicsEnvironment
java.endorsed.dirs: C:\Program Files\Java\jre1.8.0_211\lib\endorsed
os.arch: amd64
java.io.tmpdir: C:\Users\Peter Chan\AppData\Local\Temp\
line.separator: 
java.vm.specification.vendor: Oracle Corporation
user.variant: 
os.name: Windows 10
apple.laf.useScreenMenuBar: true
sun.jnu.encoding: Cp1252
java.library.path: C:\Program Files\Java\jre1.8.0_211\bin;C:\WINDOWS\Sun\Java\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\WINDOWS\System32\OpenSSH\;C:\Users\Peter Chan\AppData\Local\Microsoft\WindowsApps;;C:\Program Files\Java\jre1.8.0_211\bin;.
sun.awt.enableExtraMouseButtons: true
java.specification.name: Java Platform API Specification
java.class.version: 52.0
sun.management.compiler: HotSpot 64-Bit Tiered Compilers
os.version: 10.0
user.home: C:\Users\Peter Chan
user.timezone: America/Los_Angeles
catalina.useNaming: false
java.awt.printerjob: sun.awt.windows.WPrinterJob
java.specification.version: 1.8
file.encoding: Cp1252
muse.log: C:\Users\Peter Chan\epadd-settings\epadd.log
catalina.home: C:\Users\Peter Chan\AppData\Local\Temp\epadd
user.name: Peter Chan
java.class.path: C:\Users\Peter Chan\Desktop\epadd7.1.exe
java.vm.specification.version: 1.8
sun.arch.data.model: 64
java.home: C:\Program Files\Java\jre1.8.0_211
sun.java.command: C:\Users\Peter Chan\Desktop\epadd7.1.exe
java.specification.vendor: Oracle Corporation
user.language: en
awt.toolkit: sun.awt.windows.WToolkit
java.vm.info: mixed mode
java.version: 1.8.0_211
java.ext.dirs: C:\Program Files\Java\jre1.8.0_211\lib\ext;C:\WINDOWS\Sun\Java\lib\ext
muse.container: tomcat
sun.boot.class.path: C:\Program Files\Java\jre1.8.0_211\lib\resources.jar;C:\Program Files\Java\jre1.8.0_211\lib\rt.jar;C:\Program Files\Java\jre1.8.0_211\lib\sunrsasign.jar;C:\Program Files\Java\jre1.8.0_211\lib\jsse.jar;C:\Program Files\Java\jre1.8.0_211\lib\jce.jar;C:\Program Files\Java\jre1.8.0_211\lib\charsets.jar;C:\Program Files\Java\jre1.8.0_211\lib\jfr.jar;C:\Program Files\Java\jre1.8.0_211\classes
java.vendor: Oracle Corporation
catalina.base: C:\Users\Peter Chan\AppData\Local\Temp\epadd
file.separator: \
java.vendor.url.bug: http://bugreport.sun.com/bugreport/
sun.cpu.endian: little
sun.io.unicode.encoding: UnicodeLittle
sun.desktop: windows
sun.cpu.isalist: amd64
javawebstart.version: UNKNOWN

Session attributes

Session id: 163146E1E447B987FAE84C6FFABCB65D, created Tue Jun 11 12:48:17 PDT 2019, last accessed Tue Jun 11 12:52:33 PDT 2019
Session active for 0 hours, 4 minutes, 16 seconds

operationInfoMap: {}
museEmailFetcher: Muse email fetcher with 0 fetcher(s)

Last error code:null type: null 

Warnings log (from C:\Users\Peter Chan\epadd-settings\epadd.log.warnings)

11 Jun 12:47:59 Log4JUtils WARN - __________________________________________________________________________________________________________________________________________________________________________ 
Fresh deployment of ePADD started
__________________________________________________________________________________________________________________________________________________________________________ 
11 Jun 12:47:59 Log4JUtils WARN - Warnings being logged to C:\Users\Peter Chan\epadd-settings\epadd.log
11 Jun 12:49:34 JSPHelper WARN - Exception fetching/indexing emails
java.lang.NullPointerException
java.lang.NullPointerException
at edu.stanford.muse.index.Archive.prepareBaseDir(Archive.java:659)
at edu.stanford.muse.index.Archive.setup(Archive.java:588)
at edu.stanford.muse.webapp.JSPHelper.preparedArchive(JSPHelper.java:545)
at edu.stanford.muse.index.ArchiveReaderWriter.prepareAndLoadArchive(ArchiveReaderWriter.java:863)
at org.apache.jsp.ajax.async.doFetchAndIndex_jsp.doFetchAndIndex(doFetchAndIndex_jsp.java:63)
at org.apache.jsp.ajax.async.doFetchAndIndex_jsp$1.onStart(doFetchAndIndex_jsp.java:331)
at edu.stanford.epadd.util.OperationInfo.lambda$run$0(OperationInfo.java:61)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)

11 Jun 12:52:31 JSPHelper WARN - Exception fetching/indexing emails
java.lang.NullPointerException
java.lang.NullPointerException
at edu.stanford.muse.index.Archive.prepareBaseDir(Archive.java:659)
at edu.stanford.muse.index.Archive.setup(Archive.java:588)
at edu.stanford.muse.webapp.JSPHelper.preparedArchive(JSPHelper.java:545)
at edu.stanford.muse.index.ArchiveReaderWriter.prepareAndLoadArchive(ArchiveReaderWriter.java:863)
at org.apache.jsp.ajax.async.doFetchAndIndex_jsp.doFetchAndIndex(doFetchAndIndex_jsp.java:63)
at org.apache.jsp.ajax.async.doFetchAndIndex_jsp$1.onStart(doFetchAndIndex_jsp.java:331)
at edu.stanford.epadd.util.OperationInfo.lambda$run$0(OperationInfo.java:61)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)

Debug log (from C:\Users\Peter Chan\epadd-settings\epadd.log)
11 Jun 12:47:59 Log4JUtils INFO - __________________________________________________________________________________________________________________________________________________________________________ 
Fresh deployment of ePADD started
__________________________________________________________________________________________________________________________________________________________________________ 
11 Jun 12:47:59 Log4JUtils WARN - __________________________________________________________________________________________________________________________________________________________________________ 
Fresh deployment of ePADD started
__________________________________________________________________________________________________________________________________________________________________________ 
11 Jun 12:47:59 Log4JUtils INFO - Warning messages will also be recorded in C:\Users\Peter Chan\epadd-settings\epadd.log.warnings
11 Jun 12:47:59 Log4JUtils WARN - Warnings being logged to C:\Users\Peter Chan\epadd-settings\epadd.log
11 Jun 12:47:59 Log4JUtils INFO - Entity log messages will be recorded in C:\Users\Peter Chan\epadd-settings\epadd.log.entityExtractor.log
11 Jun 12:47:59 JSPHelper INFO - Filter LoggingFilter initialized
11 Jun 12:48:17 JSPHelper INFO - Session Created: 163146E1E447B987FAE84C6FFABCB65D at Tue Jun 11 12:48:17 PDT 2019
11 Jun 12:48:17 JSPHelper INFO - Current number of sessions: 1
11 Jun 12:48:17 JSPHelper INFO - NEW Request[null@0:0:0:0:0:0:0:1]: http://localhost:9099/epadd/ link: http://localhost:9099/epadd/?
11 Jun 12:48:17 JSPHelper INFO - No archive in session, trying to load default archive
11 Jun 12:48:17 JSPHelper INFO - Trying to read archive from C:\Users\Peter Chan\epadd-appraisal\user
11 Jun 12:48:17 JSPHelper INFO - Default archive = null
11 Jun 12:48:17 JSPHelper INFO - COMPLETED Request[null@0:0:0:0:0:0:0:1]: http://localhost:9099/epadd/ link: http://localhost:9099/epadd/?
11 Jun 12:48:17 JSPHelper INFO - NEW Request[null@0:0:0:0:0:0:0:1]: http://localhost:9099/epadd/email-sources link: http://localhost:9099/epadd/email-sources?
11 Jun 12:48:18 JSPHelper INFO - COMPLETED Request[null@0:0:0:0:0:0:0:1]: http://localhost:9099/epadd/email-sources link: http://localhost:9099/epadd/email-sources?
11 Jun 12:48:18 JSPHelper INFO - NEW Request[null@0:0:0:0:0:0:0:1]: http://localhost:9099/epadd/fonts/fontawesome-webfont.woff params: v -> 4.2.0 link: http://localhost:9099/epadd/fonts/fontawesome-webfont.woff?v=4.2.0&
11 Jun 12:48:18 JSPHelper INFO - COMPLETED Request[null@0:0:0:0:0:0:0:1]: http://localhost:9099/epadd/fonts/fontawesome-webfont.woff params: v -> 4.2.0 link: http://localhost:9099/epadd/fonts/fontawesome-webfont.woff?v=4.2.0&
11 Jun 12:48:18 JSPHelper INFO - NEW Request[null@0:0:0:0:0:0:0:1]: http://localhost:9099/epadd/fonts/fontawesome-webfont.ttf params: v -> 4.2.0 link: http://localhost:9099/epadd/fonts/fontawesome-webfont.ttf?v=4.2.0&
11 Jun 12:48:18 JSPHelper INFO - COMPLETED Request[null@0:0:0:0:0:0:0:1]: http://localhost:9099/epadd/fonts/fontawesome-webfont.ttf params: v -> 4.2.0 link: http://localhost:9099/epadd/fonts/fontawesome-webfont.ttf?v=4.2.0&
11 Jun 12:49:30 JSPHelper INFO - NEW Request[null@0:0:0:0:0:0:0:1]: http://localhost:9099/epadd/ajax/clearAccounts.jsp link: http://localhost:9099/epadd/ajax/clearAccounts.jsp?
11 Jun 12:49:30 JSPHelper INFO - COMPLETED Request[null@0:0:0:0:0:0:0:1]: http://localhost:9099/epadd/ajax/clearAccounts.jsp link: http://localhost:9099/epadd/ajax/clearAccounts.jsp?
11 Jun 12:49:30 JSPHelper INFO - NEW Request[null@0:0:0:0:0:0:0:1]: http://localhost:9099/epadd/ajax/doLogin.jsp params: name -> Jeb Bush alternateEmailAddrs -> archiveTitle -> Jeb Bush accountType0 -> email loginName0 -> password0 -> *** accountType1 -> imap server1 -> loginName1 -> password1 -> *** accountType2 -> mbox mboxDir2 -> /ePADD workshop/mbox1/ emailSource2 -> accountIdx -> 2 incremental -> true link: http://localhost:9099/epadd/ajax/doLogin.jsp?name=Jeb Bush&alternateEmailAddrs=&archiveTitle=Jeb Bush&accountType0=email&loginName0=&accountType1=imap&server1=&loginName1=&accountType2=mbox&mboxDir2=/ePADD workshop/mbox1/&emailSource2=&accountIdx=2&incremental=true&
11 Jun 12:49:30 Accounts INFO - adding mbox account: /ePADD workshop/mbox1/
11 Jun 12:49:30 MuseEmailFetcher INFO - Successful login for account: Folder store with rootpath = "C:\ePADD workshop\mbox1"
11 Jun 12:49:30 MuseEmailFetcher INFO - Email fetcher went from 0 stores to 1
11 Jun 12:49:30 JSPHelper INFO - COMPLETED Request[null@0:0:0:0:0:0:0:1]: http://localhost:9099/epadd/ajax/doLogin.jsp params: name -> Jeb Bush alternateEmailAddrs -> archiveTitle -> Jeb Bush accountType0 -> email loginName0 -> password0 -> *** accountType1 -> imap server1 -> loginName1 -> password1 -> *** accountType2 -> mbox mboxDir2 -> /ePADD workshop/mbox1/ emailSource2 -> accountIdx -> 2 incremental -> true link: http://localhost:9099/epadd/ajax/doLogin.jsp?name=Jeb Bush&alternateEmailAddrs=&archiveTitle=Jeb Bush&accountType0=email&loginName0=&accountType1=imap&server1=&loginName1=&accountType2=mbox&mboxDir2=/ePADD workshop/mbox1/&emailSource2=&accountIdx=2&incremental=true&
11 Jun 12:49:30 JSPHelper INFO - NEW Request[null@0:0:0:0:0:0:0:1]: http://localhost:9099/epadd/folders link: http://localhost:9099/epadd/folders?
11 Jun 12:49:30 JSPHelper INFO - Running inside container: Apache Tomcat/8.0.29
11 Jun 12:49:30 JSPHelper INFO - Running on jetty: false
11 Jun 12:49:30 JSPHelper INFO - Muse has 1 accounts
11 Jun 12:49:30 JSPHelper INFO - getting folders and counts from fetcher #0
11 Jun 12:49:30 MboxEmailStore INFO - folder cache does not exist: C:\Users\Peter Chan\epadd-appraisal\user\.muse.dir.C:--ePADD workshop--mbox1
11 Jun 12:49:30 MboxEmailStore INFO - Opening folder C:\ePADD workshop\mbox1\0........x in r/o mode...
11 Jun 12:49:30 JSPHelper INFO - NEW Request[null@0:0:0:0:0:0:0:1]: http://localhost:9099/epadd/ajax/getFolderInfos.jsp params: account -> 0 _ -> 1560282570810 link: http://localhost:9099/epadd/ajax/getFolderInfos.jsp?account=0&_=1560282570810&
11 Jun 12:49:31 EmailStore INFO - Folder infos currently available: 1
11 Jun 12:49:31 JSPHelper INFO - COMPLETED Request[null@0:0:0:0:0:0:0:1]: http://localhost:9099/epadd/ajax/getFolderInfos.jsp params: account -> 0 _ -> 1560282570810 link: http://localhost:9099/epadd/ajax/getFolderInfos.jsp?account=0&_=1560282570810&
11 Jun 12:49:32 JSPHelper INFO - NEW Request[null@0:0:0:0:0:0:0:1]: http://localhost:9099/epadd/ajax/getFolderInfos.jsp params: account -> 0 _ -> 1560282572165 link: http://localhost:9099/epadd/ajax/getFolderInfos.jsp?account=0&_=1560282572165&
11 Jun 12:49:32 EmailStore INFO - Folder infos currently available: 1
11 Jun 12:49:32 JSPHelper INFO - COMPLETED Request[null@0:0:0:0:0:0:0:1]: http://localhost:9099/epadd/ajax/getFolderInfos.jsp params: account -> 0 _ -> 1560282572165 link: http://localhost:9099/epadd/ajax/getFolderInfos.jsp?account=0&_=1560282572165&
11 Jun 12:49:33 MboxEmailStore INFO - Saving folder cache to C:\Users\Peter Chan\epadd-appraisal\user\.muse.dir.C:--ePADD workshop--mbox1
11 Jun 12:49:33 JSPHelper INFO - COMPLETED Request[null@0:0:0:0:0:0:0:1]: http://localhost:9099/epadd/folders link: http://localhost:9099/epadd/folders?
11 Jun 12:49:33 JSPHelper INFO - NEW Request[null@0:0:0:0:0:0:0:1]: http://localhost:9099/epadd/ajax/getFolderInfos.jsp params: account -> 0 _ -> 1560282573175 link: http://localhost:9099/epadd/ajax/getFolderInfos.jsp?account=0&_=1560282573175&
11 Jun 12:49:33 EmailStore INFO - Folder infos currently available: 1
11 Jun 12:49:33 JSPHelper INFO - COMPLETED Request[null@0:0:0:0:0:0:0:1]: http://localhost:9099/epadd/ajax/getFolderInfos.jsp params: account -> 0 _ -> 1560282573175 link: http://localhost:9099/epadd/ajax/getFolderInfos.jsp?account=0&_=1560282573175&
11 Jun 12:49:34 JSPHelper INFO - NEW Request[null@0:0:0:0:0:0:0:1]: http://localhost:9099/epadd/ajax/async/doFetchAndIndex.jsp params: folder -> /ePADD workshop/mbox1/^-^C:\ePADD workshop\mbox1\01Jan.mbox period -> Monthly downloadAttachments -> true opID -> 8499065 link: http://localhost:9099/epadd/ajax/async/doFetchAndIndex.jsp?folder=/ePADD workshop/mbox1/^-^C:\ePADD workshop\mbox1\01Jan.mbox&period=Monthly&downloadAttachments=true&opID=8499065&
11 Jun 12:49:34 JSPHelper INFO - request parameter encoding is UTF-8
11 Jun 12:49:34 JSPHelper INFO - COMPLETED Request[null@0:0:0:0:0:0:0:1]: http://localhost:9099/epadd/ajax/async/doFetchAndIndex.jsp params: folder -> /ePADD workshop/mbox1/^-^C:\ePADD workshop\mbox1\01Jan.mbox period -> Monthly downloadAttachments -> true opID -> 8499065 link: http://localhost:9099/epadd/ajax/async/doFetchAndIndex.jsp?folder=/ePADD workshop/mbox1/^-^C:\ePADD workshop\mbox1\01Jan.mbox&period=Monthly&downloadAttachments=true&opID=8499065&
11 Jun 12:49:34 JSPHelper INFO - Creating a new archive in C:\Users\Peter Chan\epadd-appraisal\user
11 Jun 12:49:34 BlobStore INFO - Opening file repository in C:\Users\Peter Chan\epadd-appraisal\user\data\blobs\
11 Jun 12:49:34 JSPHelper WARN - Exception fetching/indexing emails
java.lang.NullPointerException
java.lang.NullPointerException
at edu.stanford.muse.index.Archive.prepareBaseDir(Archive.java:659)
at edu.stanford.muse.index.Archive.setup(Archive.java:588)
at edu.stanford.muse.webapp.JSPHelper.preparedArchive(JSPHelper.java:545)
at edu.stanford.muse.index.ArchiveReaderWriter.prepareAndLoadArchive(ArchiveReaderWriter.java:863)
at org.apache.jsp.ajax.async.doFetchAndIndex_jsp.doFetchAndIndex(doFetchAndIndex_jsp.java:63)
at org.apache.jsp.ajax.async.doFetchAndIndex_jsp$1.onStart(doFetchAndIndex_jsp.java:331)
at edu.stanford.epadd.util.OperationInfo.lambda$run$0(OperationInfo.java:61)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)

11 Jun 12:49:50 JSPHelper INFO - NEW Request[null@0:0:0:0:0:0:0:1]: http://localhost:9099/epadd/debug params: archiveID -> null link: http://localhost:9099/epadd/debug?archiveID=null&
11 Jun 12:49:51 JSPHelper INFO - COMPLETED Request[null@0:0:0:0:0:0:0:1]: http://localhost:9099/epadd/debug params: archiveID -> null link: http://localhost:9099/epadd/debug?archiveID=null&
11 Jun 12:52:28 JSPHelper INFO - NEW Request[null@0:0:0:0:0:0:0:1]: http://localhost:9099/epadd/ajax/getFolderInfos.jsp params: account -> 0 _ -> 1560282748076 link: http://localhost:9099/epadd/ajax/getFolderInfos.jsp?account=0&_=1560282748076&
11 Jun 12:52:28 EmailStore INFO - Folder infos currently available: 1
11 Jun 12:52:28 JSPHelper INFO - COMPLETED Request[null@0:0:0:0:0:0:0:1]: http://localhost:9099/epadd/ajax/getFolderInfos.jsp params: account -> 0 _ -> 1560282748076 link: http://localhost:9099/epadd/ajax/getFolderInfos.jsp?account=0&_=1560282748076&
11 Jun 12:52:31 JSPHelper INFO - NEW Request[null@0:0:0:0:0:0:0:1]: http://localhost:9099/epadd/ajax/async/doFetchAndIndex.jsp params: folder -> /ePADD workshop/mbox1/^-^C:\ePADD workshop\mbox1\01Jan.mbox period -> Monthly downloadAttachments -> true opID -> 2756449 link: http://localhost:9099/epadd/ajax/async/doFetchAndIndex.jsp?folder=/ePADD workshop/mbox1/^-^C:\ePADD workshop\mbox1\01Jan.mbox&period=Monthly&downloadAttachments=true&opID=2756449&
11 Jun 12:52:31 JSPHelper INFO - request parameter encoding is UTF-8
11 Jun 12:52:31 JSPHelper INFO - COMPLETED Request[null@0:0:0:0:0:0:0:1]: http://localhost:9099/epadd/ajax/async/doFetchAndIndex.jsp params: folder -> /ePADD workshop/mbox1/^-^C:\ePADD workshop\mbox1\01Jan.mbox period -> Monthly downloadAttachments -> true opID -> 2756449 link: http://localhost:9099/epadd/ajax/async/doFetchAndIndex.jsp?folder=/ePADD workshop/mbox1/^-^C:\ePADD workshop\mbox1\01Jan.mbox&period=Monthly&downloadAttachments=true&opID=2756449&
11 Jun 12:52:31 JSPHelper INFO - Creating a new archive in C:\Users\Peter Chan\epadd-appraisal\user
11 Jun 12:52:31 BlobStore INFO - Opening file repository in C:\Users\Peter Chan\epadd-appraisal\user\data\blobs\
11 Jun 12:52:31 JSPHelper WARN - Exception fetching/indexing emails
java.lang.NullPointerException
java.lang.NullPointerException
at edu.stanford.muse.index.Archive.prepareBaseDir(Archive.java:659)
at edu.stanford.muse.index.Archive.setup(Archive.java:588)
at edu.stanford.muse.webapp.JSPHelper.preparedArchive(JSPHelper.java:545)
at edu.stanford.muse.index.ArchiveReaderWriter.prepareAndLoadArchive(ArchiveReaderWriter.java:863)
at org.apache.jsp.ajax.async.doFetchAndIndex_jsp.doFetchAndIndex(doFetchAndIndex_jsp.java:63)
at org.apache.jsp.ajax.async.doFetchAndIndex_jsp$1.onStart(doFetchAndIndex_jsp.java:331)
at edu.stanford.epadd.util.OperationInfo.lambda$run$0(OperationInfo.java:61)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)

11 Jun 12:55:18 JSPHelper INFO - NEW Request[null@0:0:0:0:0:0:0:1]: http://localhost:9099/epadd/debug params: archiveID -> null link: http://localhost:9099/epadd/debug?archiveID=null&

ePADD Release 7.1 © Stanford University

**Comment by peterchanws** [comment]
UC Santa Cruz has just reported the same issue.

**Comment by oflahero** [comment]
Same for me (new to ePadd.) Using Yahoo! Mail as a source. Encountered above error also on Windows 10; but only on subsequent times clicking 'Next' in the Import wizard (where you see the folders selected), after the first failure, where I got the following error. _0.cfs is in fact present, all 72MB of it. Clicking Next after seeing this got me the NullPointerException alluded to above. Will try running as admin instead and see if that helps.

09 Jul 00:07:38 JSPHelper WARN  - Exception fetching/indexing emails
java.io.FileNotFoundException: C:\Users\Owen\epadd-appraisal\user\data\indexes\emails\_0.cfs (Access is denied)
java.io.FileNotFoundException: C:\Users\Owen\epadd-appraisal\user\data\indexes\emails\_0.cfs (Access is denied)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at org.apache.commons.io.FileUtils.doCopyFile(FileUtils.java:1138)
	at org.apache.commons.io.FileUtils.doCopyDirectory(FileUtils.java:1428)
	at org.apache.commons.io.FileUtils.doCopyDirectory(FileUtils.java:1426)
	at org.apache.commons.io.FileUtils.doCopyDirectory(FileUtils.java:1426)
	at org.apache.commons.io.FileUtils.copyDirectory(FileUtils.java:1389)
	at org.apache.commons.io.FileUtils.copyDirectory(FileUtils.java:1261)
	at org.apache.commons.io.FileUtils.copyDirectory(FileUtils.java:1230)
	at org.apache.commons.io.FileUtils.moveDirectory(FileUtils.java:2755)
	at edu.stanford.muse.index.ArchiveReaderWriter.saveArchive(ArchiveReaderWriter.java:362)
	at edu.stanford.muse.index.ArchiveReaderWriter.saveArchive(ArchiveReaderWriter.java:285)
	at org.apache.jsp.ajax.async.doFetchAndIndex_jsp.doFetchAndIndex(doFetchAndIndex_jsp.java:131)
	at org.apache.jsp.ajax.async.doFetchAndIndex_jsp$1.onStart(doFetchAndIndex_jsp.java:331)
	at edu.stanford.epadd.util.OperationInfo.lambda$run$0(OperationInfo.java:61)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
not before the first time it tried processing the emails with the follow

**Comment by oflahero** [comment]
Running as admin made no difference. File in question appeared to be locked even for reading; it was deleted after quitting ePadd.

**Comment by peterchanws** [comment]
ver 7.1
problem fixed.

**Comment by hamdigarch** [comment]
I'm having the same problem as in original post. Running v7.2 on Windows 10. Submitted report via email earlier today with log file. The basics are:
- during import
- select folders
- system processes
- identifies entities
- begins "saving to archive" stage
- then "Exception fetching/indexing emails"

Have tried removing ePADD and reinstalling; 4 different email accounts that started in a variety of formats and sizes, all converted by Emailchemy; same results every time. Any ideas? Thanks for your help.

**Comment by hangal** [comment]
@hamdigarch could you please send us the log files? (Click on "Report a problem" at top right)
Please send them via email (not post them here).
Thanks, we'll look into it at the earliest.

**Comment by hamdigarch** [comment]
> @hamdigarch could you please send us the log files? (Click on "Report a problem" at top right)
> Please send them via email (not post them here).
> Thanks, we'll look into it at the earliest.

Hi @hangal. I did report this via the method you reference on the same day as I made my post. If that email has not come through, please let me know.

**Comment by hangal** [comment]
might be the same as #373

**Comment by hamdigarch** [comment]
This issue was resolved in a later version 7.x, but I have just installed version 8 (on a Windows 10 machine) and am now having the same problem again. I will submit my log files via email, but wanted to note it here as well.

**Comment by hangal** [comment]
This could be a problem with file locking on Windows.
We need to debug it further. Have seen the problem on and off and it seems to be Windows-related.

**Comment by tomhigginsuom** [comment]
Please retry on the latest version.
