### ISSUE TITLE
Exception fetching/indexing emails

### ISSUE THREAD

**Issue by emelinelevasseur** [ePADD/epadd#438]
Platform : Windows 10 64 bits
RAM : 16 Go
Java : 
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)
Epadd : 10.0 (and previously 9 and 8)

After selecting the folders I wanted to import and hitting “Next”, I encountered an “Exception fetching/indexing emails” message. This issue happens on every Windows machine at the French National Archives. There doesn’t seem to be any problem on Mac (tested on one machine).
We encountered this problem with other versions of Epadd (8 et 9) in previous tests. We’ve seen a similar report on issue #365, but there hasn’t been any update since September 2021.

Logs :
27 janv. 10:59:17 EmailStore INFO  - Folder infos currently available: 125
27 janv. 10:59:20 BlobStore INFO  - Opening file repository in C:\Users\emeline.levasseur\epadd-appraisal\user\data\blobs\
27 janv. 10:59:20 Util ERROR - Exception fetching/indexing emails
org.apache.lucene.store.LockObtainFailedException: Lock held by this virtual machine: C:\Users\emeline.levasseur\epadd-appraisal\user\data\indexes\emails\write.lock
	at org.apache.lucene.store.NativeFSLockFactory.obtainFSLock(NativeFSLockFactory.java:139) ~[lucene-core-7.2.1.jar:7.2.1 b2b6438b37073bee1fca40374e85bf91aa457c0b - ubuntu - 2018-01-10 00:48:43]
	at org.apache.lucene.store.FSLockFactory.obtainLock(FSLockFactory.java:41) ~[lucene-core-7.2.1.jar:7.2.1 b2b6438b37073bee1fca40374e85bf91aa457c0b - ubuntu - 2018-01-10 00:48:43]
	at org.apache.lucene.store.BaseDirectory.obtainLock(BaseDirectory.java:45) ~[lucene-core-7.2.1.jar:7.2.1 b2b6438b37073bee1fca40374e85bf91aa457c0b - ubuntu - 2018-01-10 00:48:43]
	at org.apache.lucene.index.IndexWriter.<init>(IndexWriter.java:948) ~[lucene-core-7.2.1.jar:7.2.1 b2b6438b37073bee1fca40374e85bf91aa457c0b - ubuntu - 2018-01-10 00:48:43]
	at edu.stanford.muse.index.Indexer.openIndexWriter(Indexer.java:662) ~[classes/:?]
	at edu.stanford.muse.index.Indexer.<init>(Indexer.java:221) ~[classes/:?]
	at edu.stanford.muse.index.Archive.setup(Archive.java:975) ~[classes/:?]
	at edu.stanford.muse.webapp.JSPHelper.preparedArchive(JSPHelper.java:559) ~[classes/:?]
	at edu.stanford.muse.index.ArchiveReaderWriter.prepareAndLoadArchive(ArchiveReaderWriter.java:1027) ~[classes/:?]
	at org.apache.jsp.ajax.async.doFetchAndIndex_jsp.doFetchAndIndex(doFetchAndIndex_jsp.java:63) ~[?:?]
	at org.apache.jsp.ajax.async.doFetchAndIndex_jsp$1.onStart(doFetchAndIndex_jsp.java:341) ~[?:?]
	at edu.stanford.epadd.util.OperationInfo.lambda$run$0(OperationInfo.java:61) ~[classes/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:834) ~[?:?]

**Comment by jfarwer** [comment]
Does this happen every time you try to import? Or only with certain emails? Have you ever managed to import any emails on Windows?

**Comment by emelinelevasseur** [comment]
Unfortunately it happens every time ... We've never managed to import any emails on Windows (first time was with ePADD 8).

**Comment by jfarwer** [comment]
Would you be able to share the log files epadd.log and epadd.log.warnings in epadd-settings?

**Comment by emelinelevasseur** [comment]
Here there are ! I've added ".txt" to the epadd.log.warnings to be able to attach it to my message. Thank you !
[epadd.log](https://github.com/ePADD/epadd/files/10685789/epadd.log)
[epadd.log.warnings.txt](https://github.com/ePADD/epadd/files/10685793/epadd.log.warnings.txt)

**Comment by jfarwer** [comment]
Thanks, that is helpful. Could you please try ePADD v10.0.2 (the latest release)?

**Comment by jfarwer** [comment]
Great, thanks for the feedback.

**Comment by lyndasf** [comment]
![image](https://user-images.githubusercontent.com/74563310/222809860-af984bde-752b-428d-ad32-9ada03be51f9.png)
![image](https://user-images.githubusercontent.com/74563310/222809891-51a953a1-f351-49b2-b382-7c7aa1b94752.png)
![image](https://user-images.githubusercontent.com/74563310/222809986-ab378b35-b28e-4eae-822a-5970e568741e.png)

**Comment by jfarwer** [comment]
Have you tried firing up ePADD from the CLI in Windows? What happens?

Thanks

**Comment by lyndasf** [comment]
Yes, this is from the CLI.

Lynda

**Comment by jfarwer** [comment]
Do you have a folder 'rules' with a file 'gazettes.ser.gz' in your epadd-settings folder (which should be in the home directory)?

Jochen

**Comment by lyndasf** [comment]
Thank you. That folder was not there. Strange. I have copied one over and did a successful run of a smaller account.

**Comment by jfarwer** [comment]
Glad it works. Thanks for the feedback.
