### ISSUE TITLE
ERROR - Resource missing help browseMessages.help.appraisal 

### ISSUE THREAD

**Issue by sshipley64** [ePADD/epadd#475]
After changing the personal lexicon to shorten it and creating a label for "Not Reviewed" (And initially labeling all messages "Not Reviewed" so I can easily filter),  I always get a resource missing help browseMessages.help.appraisal after labeling many of the messages Do not Transfer and Reviewed and unsetting Not Reviewed. and trying to filter for Not Reviewed on the left navigation. 

When looking at the logs I get 

08 Oct 08:46:43 Indexer INFO  - 631 docs added to docIdMap cache
08 Oct 08:46:43 Indexer INFO  - Looking up term: divorce|spouse|wife|husband|daughter|son|dad|mom|stepson|stepdaughter took: 104
08 Oct 08:46:43 Indexer INFO  - Took: 0ms for query:(body:divorc title:divorc to_names:divorce from_names:divorce cc_names:divorce bcc_names:divorce to_emails:divorce from_emails:divorce cc_emails:divorce bcc_emails:divorce) (body:spous title:spous to_names:spouse from_names:spouse cc_names:spouse bcc_names:spouse to_emails:spouse from_emails:spouse cc_emails:spouse bcc_emails:spouse) (body:wife title:wife to_names:wife from_names:wife cc_names:wife bcc_names:wife to_emails:wife from_emails:wife cc_emails:wife bcc_emails:wife) (body:husband title:husband to_names:husband from_names:husband cc_names:husband bcc_names:husband to_emails:husband from_emails:husband cc_emails:husband bcc_emails:husband) (body:daughter title:daughter to_names:daughter from_names:daughter cc_names:daughter bcc_names:daughter to_emails:daughter from_emails:daughter cc_emails:daughter bcc_emails:daughter) (body:son title:son to_names:son from_names:son cc_names:son bcc_names:son to_emails:son from_emails:son cc_emails:son bcc_emails:son) (body:dad title:dad to_names:dad from_names:dad cc_names:dad bcc_names:dad to_emails:dad from_emails:dad cc_emails:dad bcc_emails:dad) (body:mom title:mom to_names:mom from_names:mom cc_names:mom bcc_names:mom to_emails:mom from_emails:mom cc_emails:mom bcc_emails:mom) (body:stepson title:stepson to_names:stepson from_names:stepson cc_names:stepson bcc_names:stepson to_emails:stepson from_emails:stepson cc_emails:stepson bcc_emails:stepson) (body:stepdaught title:stepdaught to_names:stepdaughter from_names:stepdaughter cc_names:stepdaughter bcc_names:stepdaughter to_emails:stepdaughter from_emails:stepdaughter cc_emails:stepdaughter bcc_emails:stepdaughter)
08 Oct 08:46:43 Indexer INFO  - Existing entry for dir name to docIdMap
08 Oct 08:46:43 Indexer INFO  - Found: 1 hits for query: divorce|spouse|wife|husband|daughter|son|dad|mom|stepson|stepdaughter
08 Oct 08:46:43 Indexer INFO  - 1 docs added to docIdMap cache
08 Oct 08:46:43 Messages ERROR - Resource missing help browseMessages.help.appraisal
java.util.MissingResourceException: Can't find resource for bundle java.util.PropertyResourceBundle, key browseMessages.help.appraisal
	at java.util.ResourceBundle.getObject(ResourceBundle.java:567) ~[?:?]
	at java.util.ResourceBundle.getObject(ResourceBundle.java:561) ~[?:?]
	at java.util.ResourceBundle.getString(ResourceBundle.java:523) ~[?:?]
	at edu.stanford.muse.util.Messages.getMessage(Messages.java:77) ~[classes/:?]
	at edu.stanford.muse.util.Messages.getMessage(Messages.java:52) ~[classes/:?]
	at org.apache.jsp.browse_jsp._jspService(browse_jsp.java:1184) ~[?:?]
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70) ~[epadd-standalone.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764) ~[epadd-standalone.jar:?]
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:466) ~[epadd-standalone.jar:?]
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:379) ~[epadd-standalone.jar:?]
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:327) ~[epadd-standalone.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764) ~[epadd-standalone.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227) ~[epadd-standalone.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[epadd-standalone.jar:?]
	at edu.stanford.muse.webapp.LoggingFilter.doFilter(LoggingFilter.java:23) ~[classes/:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[epadd-standalone.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[epadd-standalone.jar:?]
	at org.apache.logging.log4j.web.Log4jServletFilter.doFilter(Log4jServletFilter.java:71) ~[log4j-web-2.18.0.jar:2.18.0]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[epadd-standalone.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[epadd-standalone.jar:?]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197) ~[epadd-standalone.jar:?]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) ~[epadd-standalone.jar:?]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) ~[epadd-standalone.jar:?]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135) ~[epadd-standalone.jar:?]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) ~[epadd-standalone.jar:?]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) ~[epadd-standalone.jar:?]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360) ~[epadd-standalone.jar:?]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399) ~[epadd-standalone.jar:?]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[epadd-standalone.jar:?]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:890) ~[epadd-standalone.jar:?]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1789) ~[epadd-standalone.jar:?]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[epadd-standalone.jar:?]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[epadd-standalone.jar:?]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[epadd-standalone.jar:?]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[epadd-standalone.jar:?]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]

*

**Screenshots**
![image](https://github.com/user-attachments/assets/3b645c8c-cfab-4b15-8068-9366695543d5)

**Desktop (please complete the following information):**
 - OS: Ubuntu 24.04 LTS
 - Chrome
 - ePADD Version 11.2
 - Java Version [e.g. 11] openjdk version 21.0.4 2024-07-16

**Additional context**
attaching log files.  Can provide mbox. 
[useful files.zip](https://github.com/user-attachments/files/17299994/useful.files.zip)

**Comment by jfarwer** [comment]
Sorry, when I click the screenshot, it says 'Cannot find page'. What happens to ePADD when the error occurs? Does it crash? Thanks

**Comment by jfarwer** [comment]
I can click the screenshots now. So does ePADD stop working when the error occurs? Thanks

**Comment by sshipley64** [comment]
It shows the snap page on chrome and you can go back and browse,  but it will give the same error if you try to label anything and it will give you "There was an error on the server. status: error error:" if you try to export to the processing module.

**Comment by sshipley64** [comment]
It's public record so I can share.   I'll zip and include a link to it.

**Comment by sshipley64** [comment]
I need an email address to share the file with....

**Comment by jfarwer** [comment]
I have send you an email you can reply to.

**Comment by sshipley64** [comment]
This should work now: https://seattlegov-my.sharepoint.com/:u:/g/personal/sarah_shipley_seattle_gov/EcTodVyO4fVEiymiA3jhe9sBQ6q6vj1iAO2a6jDfLWC_hA?email=reply%2BACM5FLHDN67Q4LSDZKRHIZOFCNJUDEVBNHHJS4PMZ4%40reply.github.com&e=HpCEdD

**Comment by sshipley64** [comment]
.headerBackgroundMsoTable {
        border-spacing: 0px;
        width: 100%;
    }
    


    
          
            
              
                
                    
                        
                            


    
        
            
            
                
                
                
                        
                                
                                    

                                
                                                    
                                    
                
                
            
            
        
    


                        
                    
                    
                        
                            

    
        
             
             
             
        
        
             
            Hello,
        
        
             
            
For security purposes, you must enter the code below to verify your account to access MantillaArchive.zip. The code will only work for 15 minutes and if you request a new code, this code will stop working.            
        
        
             
            
                
                    
                        
                            Account verification code:
                        
                        
                            42873225
                        
                    
                
            
        
        
             
            Having problems with the code?
        
        
             
            View the error and make sure that the email identifier is "7T25Q7C". If it's not, look for an updated email or try requesting a new code.
        
    

                        
                    
                    
                        
                            


    
        
            
                
                                            
                            
                                

                            
                        
                                            
                            
                                
                                    
                                         

Privacy Statement


 
                                    
                                
                            
                        
                    
                        
                            
                                
                                    
                                        This email is generated through City of Seattle's use of Microsoft 365.

**Comment by sshipley64** [comment]
.headerBackgroundMsoTable {
        border-spacing: 0px;
        width: 100%;
    }
    


    
          
            
              
                
                    
                        
                            


    
        
            
            
                
                
                
                        
                                
                                    

                                
                                                    
                                    
                
                
            
            
        
    


                        
                    
                    
                        
                            

    
        
             
             
             
        
        
             
            Hello,
        
        
             
            
For security purposes, you must enter the code below to verify your account to access MantillaArchive.zip. The code will only work for 15 minutes and if you request a new code, this code will stop working.            
        
        
             
            
                
                    
                        
                            Account verification code:
                        
                        
                            24886593
                        
                    
                
            
        
        
             
            Having problems with the code?
        
        
             
            View the error and make sure that the email identifier is "RKFNC6B". If it's not, look for an updated email or try requesting a new code.
        
    

                        
                    
                    
                        
                            


    
        
            
                
                                            
                            
                                

                            
                        
                                            
                            
                                
                                    
                                         

Privacy Statement


 
                                    
                                
                            
                        
                    
                        
                            
                                
                                    
                                        This email is generated through City of Seattle's use of Microsoft 365.

**Comment by jfarwer** [comment]
Do you see this kind of error essage: ?
![error](https://github.com/user-attachments/assets/6b92a310-4af8-44b9-997d-34721e2b2744)

**Comment by sshipley64** [comment]
No I never got that.

**Comment by jfarwer** [comment]
Have you restarted ePADD? What happens? It will soon show the snap page?

**Comment by sshipley64** [comment]
I restarted and it shows the snap page.  I even completely reloaded the archive from the mbox and it does the same thing.

**Comment by jfarwer** [comment]
At what point did the error occur when you imported the mbox files from scratch?

**Comment by sshipley64** [comment]
After labeling a good number of them again.  I can run through it again  and tell you exactly.

**Comment by jfarwer** [comment]
Thanks that would be helpful.

**Comment by sshipley64** [comment]
May take me a day or two.   I'll note exactly each step.

**Comment by jfarwer** [comment]
Do you run ePADD using:

java -jar epadd-standalone.jar

If so, could you please try:

java -jar epadd-standalone.jar 2>&1 | tee output.dat

And, after the error occured, send me the output.dat file?

Many thanks

**Comment by sshipley64** [comment]
I do--I do alot of large collections so I set the allotted memory.  I'm importing the mbox now,  but I'll restart after with the output.dat.

**Comment by sshipley64** [comment]
Okay.  I've included the output.dat and a word doc of the steps I went through. https://seattlegov-my.sharepoint.com/:u:/r/personal/sarah_shipley_seattle_gov/Documents/[outputandsteps.zip](https://seattlegov-my.sharepoint.com/:u:/r/personal/sarah_shipley_seattle_gov/Documents/outputandsteps.zip?csf=1&web=1&e=Wwm6Io)?csf=1&web=1&e=Wwm6Io

**Comment by jfarwer** [comment]
Thanks. It says I don't have permission to access. Could you please check?

**Comment by sshipley64** [comment]
I tried adding ACM5FLDP6SRR5DPGRL62OMOFCTL6JEVBNHHJS4PMZ4@reply.github.com again and it says it's not a valid email address

**Comment by jfarwer** [comment]
I have sent you an email. Can you make it accessible from the address I have sent from?

**Comment by sshipley64** [comment]
[Share image]

Shipley, Sarah shared a file with you

Here's the document that Shipley, Sarah shared with you.

<https://seattlegov-my.sharepoint.com/:u:/g/personal/sarah_shipley_seattle_gov/EX8eENeVKdNEmBXWwuuXEQsB53fQoUcXoHWNCU0Y_ksuRQ?e=4%3AsV6YFa>
[icon]  outputandsteps
[permission globe icon]         This link only works for the direct recipients of this message.
Open <https://seattlegov-my.sharepoint.com/:u:/g/personal/sarah_shipley_seattle_gov/EX8eENeVKdNEmBXWwuuXEQsB53fQoUcXoHWNCU0Y_ksuRQ?e=4%3AsV6YFa>
[cid:0fa606b9-dcb4-4e13-b523-4719fd56ea81]

This email is generated through City of Seattle's use of Microsoft 365 and may contain content that is controlled by City of Seattle.

**Comment by sshipley64** [comment]
Okay,  I just added again.

**Comment by jfarwer** [comment]
Hmm, it says, 'Sorry, this email address isn't associated with this secure link'. Could you try again please?

**Comment by sshipley64** [comment]
[Share image]

Shipley, Sarah shared a file with you

Here's the document that Shipley, Sarah shared with you.

<https://seattlegov-my.sharepoint.com/:u:/g/personal/sarah_shipley_seattle_gov/EX8eENeVKdNEmBXWwuuXEQsBdYvjP5s57MiJ-Yn8Ezii6Q?e=4%3AgIStIG>
[icon]  outputandsteps
[permission globe icon]         This link only works for the direct recipients of this message.
Open <https://seattlegov-my.sharepoint.com/:u:/g/personal/sarah_shipley_seattle_gov/EX8eENeVKdNEmBXWwuuXEQsBdYvjP5s57MiJ-Yn8Ezii6Q?e=4%3AgIStIG>
[cid:71a80684-deb3-4132-a928-2cb9a9193fca]

This email is generated through City of Seattle's use of Microsoft 365 and may contain content that is controlled by City of Seattle.

**Comment by sshipley64** [comment]
Just added again.

**Comment by jfarwer** [comment]
Sorry, still doesn't work.

**Comment by sshipley64** [comment]
[Share image]

Shipley, Sarah shared a file with you

SMA output

<https://seattlegov-my.sharepoint.com/:u:/g/personal/sarah_shipley_seattle_gov/EX8eENeVKdNEmBXWwuuXEQsBdYvjP5s57MiJ-Yn8Ezii6Q?e=4%3AkyRoaa>
[icon]  outputandsteps
[permission globe icon]         This link only works for the direct recipients of this message.
Open <https://seattlegov-my.sharepoint.com/:u:/g/personal/sarah_shipley_seattle_gov/EX8eENeVKdNEmBXWwuuXEQsBdYvjP5s57MiJ-Yn8Ezii6Q?e=4%3AkyRoaa>
[cid:2f202d34-4685-4eda-86e9-a2092b6b5718]

This email is generated through City of Seattle's use of Microsoft 365 and may contain content that is controlled by City of Seattle.

**Comment by sshipley64** [comment]
This is the email to use correct?
reply+ACM5FLDP6SRR5DPGRL62OMOFCTL6JEVBNHHJS4PMZ4@reply.github.com

![image](https://github.com/user-attachments/assets/f98a9749-8e6f-420f-a705-aa4287e9fbaf)

**Comment by sshipley64** [comment]
.headerBackgroundMsoTable {
        border-spacing: 0px;
        width: 100%;
    }
    


    
          
            
              
                
                    
                        
                            


    
        
            
            
                
                
                
                        
                                
                                    

                                
                                                    
                                    
                
                
            
            
        
    


                        
                    
                    
                        
                            

    
        
             
             
             
        
        
             
            Hello,
        
        
             
            
For security purposes, you must enter the code below to verify your account to access outputandsteps.zip. The code will only work for 15 minutes and if you request a new code, this code will stop working.            
        
        
             
            
                
                    
                        
                            Account verification code:
                        
                        
                            85062740
                        
                    
                
            
        
        
             
            Having problems with the code?
        
        
             
            View the error and make sure that the email identifier is "KCK453C". If it's not, look for an updated email or try requesting a new code.
        
    

                        
                    
                    
                        
                            


    
        
            
                
                                            
                            
                                

                            
                        
                                            
                            
                                
                                    
                                         

Privacy Statement


 
                                    
                                
                            
                        
                    
                        
                            
                                
                                    
                                        This email is generated through City of Seattle's use of Microsoft 365.

**Comment by jfarwer** [comment]
That worked, thanks.

**Comment by jfarwer** [comment]
Could you try using a different browser? For example, after starting ePADD, open Firefox and go to localhost:9099/epadd/.

**Comment by jfarwer** [comment]
Actually, it's probably worth trying both. Maybe start by seeing what happens when you try Firefox after it stops working in Chrome.

**Comment by sshipley64** [comment]
Will do.

**Comment by sshipley64** [comment]
Okay.  I started from the Chrome loaded import and I got no errors going through the same steps on that particular lexicon category.   I loaded the mbox from scratch in Firefox,  and it doesn't have any errors going through that lexicon either.   I guess it's a Chrome issue then...   I'll continue working in Firefox.

**Comment by jfarwer** [comment]
Thanks. Let me know if there are any issues.

**Comment by sshipley64** [comment]
[Share image]

Shipley, Sarah shared a file with you

SMA Importing issue

<https://seattlegov-my.sharepoint.com/:u:/g/personal/sarah_shipley_seattle_gov/ESgG6aGCFO5BlGadd39c-H4BaGhRy_F1Kslc8GPOMTwXaw?e=4%3AakwOnb>
[icon]  useful files
[permission globe icon]         This link only works for the direct recipients of this message.
Open <https://seattlegov-my.sharepoint.com/:u:/g/personal/sarah_shipley_seattle_gov/ESgG6aGCFO5BlGadd39c-H4BaGhRy_F1Kslc8GPOMTwXaw?e=4%3AakwOnb>
[cid:c0f1f2c0-4c32-4664-9515-45b6bdcff158]

This email is generated through City of Seattle's use of Microsoft 365 and may contain content that is controlled by City of Seattle.

**Comment by sshipley64** [comment]
[Share image]

Shipley, Sarah shared a file with you

Here's the document that Shipley, Sarah shared with you.

<https://seattlegov-my.sharepoint.com/:u:/g/personal/sarah_shipley_seattle_gov/Ea-kNvXAg09PkLH5XRHS7_8BsOMWy7s7Js7F9kjRlbqAbg?e=4%3A1nrR3h>
[icon]  Hahn
[permission globe icon]         This link only works for the direct recipients of this message.
Open <https://seattlegov-my.sharepoint.com/:u:/g/personal/sarah_shipley_seattle_gov/Ea-kNvXAg09PkLH5XRHS7_8BsOMWy7s7Js7F9kjRlbqAbg?e=4%3A1nrR3h>
[cid:215fabf2-1f4c-4fdc-aab6-f6da59491d03]

This email is generated through City of Seattle's use of Microsoft 365 and may contain content that is controlled by City of Seattle.

**Comment by sshipley64** [comment]
[Share image]

Shipley, Sarah shared a file with you

Here's the document that Shipley, Sarah shared with you.

<https://seattlegov-my.sharepoint.com/:u:/g/personal/sarah_shipley_seattle_gov/ESgG6aGCFO5BlGadd39c-H4BaGhRy_F1Kslc8GPOMTwXaw?e=4%3Alb41Db>
[icon]  useful files
[permission globe icon]         This link only works for the direct recipients of this message.
Open <https://seattlegov-my.sharepoint.com/:u:/g/personal/sarah_shipley_seattle_gov/ESgG6aGCFO5BlGadd39c-H4BaGhRy_F1Kslc8GPOMTwXaw?e=4%3Alb41Db>
[cid:124e42b7-c1cd-4aa2-b1bc-87b21fa0b6fd]

This email is generated through City of Seattle's use of Microsoft 365 and may contain content that is controlled by City of Seattle.

**Comment by sshipley64** [comment]
[Share image]

Shipley, Sarah shared a file with you

Here's the document that Shipley, Sarah shared with you.

<https://seattlegov-my.sharepoint.com/:u:/g/personal/sarah_shipley_seattle_gov/Ea-kNvXAg09PkLH5XRHS7_8BsOMWy7s7Js7F9kjRlbqAbg?e=4%3AEhKHSS>
[icon]  Hahn
[permission globe icon]         This link only works for the direct recipients of this message.
Open <https://seattlegov-my.sharepoint.com/:u:/g/personal/sarah_shipley_seattle_gov/Ea-kNvXAg09PkLH5XRHS7_8BsOMWy7s7Js7F9kjRlbqAbg?e=4%3AEhKHSS>
[cid:286e1d81-813a-4a1a-a32a-7e683464c4c4]

This email is generated through City of Seattle's use of Microsoft 365 and may contain content that is controlled by City of Seattle.

**Comment by sshipley64** [comment]
.headerBackgroundMsoTable {
        border-spacing: 0px;
        width: 100%;
    }
    


    
          
            
              
                
                    
                        
                            


    
        
            
            
                
                
                
                        
                                
                                    

                                
                                                    
                                    
                
                
            
            
        
    


                        
                    
                    
                        
                            

    
        
             
             
             
        
        
             
            Hello,
        
        
             
            
For security purposes, you must enter the code below to verify your account to access useful files.zip. The code will only work for 15 minutes and if you request a new code, this code will stop working.            
        
        
             
            
                
                    
                        
                            Account verification code:
                        
                        
                            26816856
                        
                    
                
            
        
        
             
            Having problems with the code?
        
        
             
            View the error and make sure that the email identifier is "WWMH41B". If it's not, look for an updated email or try requesting a new code.
        
    

                        
                    
                    
                        
                            


    
        
            
                
                                            
                            
                                

                            
                        
                                            
                            
                                
                                    
                                         

Privacy Statement


 
                                    
                                
                            
                        
                    
                        
                            
                                
                                    
                                        This email is generated through City of Seattle's use of Microsoft 365.

**Comment by sshipley64** [comment]
.headerBackgroundMsoTable {
        border-spacing: 0px;
        width: 100%;
    }
    


    
          
            
              
                
                    
                        
                            


    
        
            
            
                
                
                
                        
                                
                                    

                                
                                                    
                                    
                
                
            
            
        
    


                        
                    
                    
                        
                            

    
        
             
             
             
        
        
             
            Hello,
        
        
             
            
For security purposes, you must enter the code below to verify your account to access useful files.zip. The code will only work for 15 minutes and if you request a new code, this code will stop working.            
        
        
             
            
                
                    
                        
                            Account verification code:
                        
                        
                            96850641
                        
                    
                
            
        
        
             
            Having problems with the code?
        
        
             
            View the error and make sure that the email identifier is "ZNH1PLB". If it's not, look for an updated email or try requesting a new code.
        
    

                        
                    
                    
                        
                            


    
        
            
                
                                            
                            
                                

                            
                        
                                            
                            
                                
                                    
                                         

Privacy Statement


 
                                    
                                
                            
                        
                    
                        
                            
                                
                                    
                                        This email is generated through City of Seattle's use of Microsoft 365.

**Comment by sshipley64** [comment]
.headerBackgroundMsoTable {
        border-spacing: 0px;
        width: 100%;
    }
    


    
          
            
              
                
                    
                        
                            


    
        
            
            
                
                
                
                        
                                
                                    

                                
                                                    
                                    
                
                
            
            
        
    


                        
                    
                    
                        
                            

    
        
             
             
             
        
        
             
            Hello,
        
        
             
            
For security purposes, you must enter the code below to verify your account to access useful files.zip. The code will only work for 15 minutes and if you request a new code, this code will stop working.            
        
        
             
            
                
                    
                        
                            Account verification code:
                        
                        
                            75372571
                        
                    
                
            
        
        
             
            Having problems with the code?
        
        
             
            View the error and make sure that the email identifier is "S2M0LLB". If it's not, look for an updated email or try requesting a new code.
        
    

                        
                    
                    
                        
                            


    
        
            
                
                                            
                            
                                

                            
                        
                                            
                            
                                
                                    
                                         

Privacy Statement


 
                                    
                                
                            
                        
                    
                        
                            
                                
                                    
                                        This email is generated through City of Seattle's use of Microsoft 365.

**Comment by jfarwer** [comment]
What kind of error do you get? Thanks

**Comment by jfarwer** [comment]
OK, thanks. Let me know if you have any other issues.
