### ISSUE TITLE
Better error messaging when out of disk space

### ISSUE THREAD

**Issue by peterchanws** [ePADD/epadd#50]
ePADD version 1.1RC3 

User reported ePADD error.

java.io.IOException: There is not enough space on the disk
Session active for 7 hours, 43 minutes, 9 seconds

It is desirable to let users kown the problem is out of disk space.

**Comment by hangal** [comment]
@vihari can you pls replicate this with a small disk volume on mac os?

**Comment by vihari** [comment]
@hangal Replicate what? The disk space problem or error reporting?
@peterchanws I don't understand, the reported ePADD error already says not enough disk space.

**Comment by peterchanws** [comment]
User get a message saying epadd error. contact pchan3@stanford.edu after epadd working 7 hrs. on the archive. It would be better if ePADD can tell user "Not Enough Disk Space" instead of just epadd error.

**Comment by vihari** [comment]
duplicate of #17

**Comment by hangal** [comment]
@vihari #17 is about main memory.
this one is about disk space.

I think what Peter is saying is that the disk space exception is logged in the log file, but not reported as a disk space error to the user. Peter, I think this is from Stephan, and I don't think we have the full log file. can you send it to us by email (or post the stack trace near the line 
java.io.IOException: There is not enough space on the disk)
That will help debug and fix.

**Comment by hangal** [comment]
So the error trace is:
at edu.stanford.muse.index.Indexer.add1DocToIndex(Indexer.java:1075)
31 Jan 20:13:42 Indexer WARN - 
java.io.IOException: There is not enough space on the disk
java.io.IOException: There is not enough space on the disk
at java.io.RandomAccessFile.writeBytes(Native Method)
at java.io.RandomAccessFile.write(Unknown Source)
at org.apache.lucene.store.FSDirectory$FSIndexOutput.flushBuffer(FSDirectory.java:452)
at org.apache.lucene.store.BufferedIndexOutput.flushBuffer(BufferedIndexOutput.java:113)
at org.apache.lucene.store.BufferedIndexOutput.flush(BufferedIndexOutput.java:102)
at org.apache.lucene.store.BufferedIndexOutput.writeBytes(BufferedIndexOutput.java:92)
at org.apache.lucene.codecs.compressing.LZ4.encodeLiterals(LZ4.java:157)
at org.apache.lucene.codecs.compressing.LZ4.encodeSequence(LZ4.java:170)
at org.apache.lucene.codecs.compressing.LZ4.compress(LZ4.java:243)
at org.apache.lucene.codecs.compressing.CompressionMode$LZ4FastCompressor.compress(CompressionMode.java:161)
at org.apache.lucene.codecs.compressing.CompressingStoredFieldsWriter.flush(CompressingStoredFieldsWriter.java:230)
at org.apache.lucene.codecs.compressing.CompressingStoredFieldsWriter.finishDocument(CompressingStoredFieldsWriter.java:160)
at org.apache.lucene.index.StoredFieldsProcessor.finishDocument(StoredFieldsProcessor.java:128)
at org.apache.lucene.index.TwoStoredFieldsConsumers.finishDocument(TwoStoredFieldsConsumers.java:65)
at org.apache.lucene.index.DocFieldProcessor.finishDocument(DocFieldProcessor.java:267)
at org.apache.lucene.index.DocumentsWriterPerThread.updateDocument(DocumentsWriterPerThread.java:271)
at org.apache.lucene.index.DocumentsWriter.updateDocument(DocumentsWriter.java:453)
at org.apache.lucene.index.IndexWriter.updateDocument(IndexWriter.java:1529)
at org.apache.lucene.index.IndexWriter.addDocument(IndexWriter.java:1199)
at org.apache.lucene.index.IndexWriter.addDocument(IndexWriter.java:1180)
at edu.stanford.muse.index.Indexer.add1DocToIndex(Indexer.java:1075)
at edu.stanford.muse.index.Indexer.indexSubdoc(Indexer.java:1107)
at edu.stanford.muse.index.Archive.addDoc(Archive.java:642)
at edu.stanford.muse.email.EmailFetcherThread.fetchAndIndexMessages(EmailFetcherThread.java:1152)
at edu.stanford.muse.email.EmailFetcherThread.run(EmailFetcherThread.java:1309)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)

Vihari, could you check this out and figure out a proper mechanism to bail out if we're out of space?
I guess we should exit cleanly -- close the index and keep as many messages as have been indexed.
It should be possible to create more space on the partition, and restart the indexing again. 

A user message needs to go back to the user too. And the out of space error needs to be logged so it is in import statistics.

**Comment by peterchanws** [comment]
Ask users to estimate the size of the archive and ensure the drive have free space for double the size.
