### ISSUE TITLE
Error when exporting to delivery and discover

### ISSUE THREAD

**Issue by peterchanws** [ePADD/epadd#68]
Full log in email

03 May 09:51:56 NER WARN - Retain only names method received null offset, redacting the entire text
03 May 09:51:56 NER WARN - Retain only names method received null offset, redacting the entire text
03 May 09:51:56 JSPHelper WARN - Error page reached. code:500 message:An exception occurred processing JSP page /export-complete-processing.jsp at line 105

102: out.println ("Exporting discovery mode archive...<br/>");
103: out.flush();
104: JSPHelper.log.info("Exporting for delivery");
105: archive.export(docsToExport, true /* public mode */, folderPublic, "default");
106: 
107: try {
108: String filename = folder + File.separator + edu.stanford.muse.Config.AUTHORITIES_CSV_FILENAME;

Stacktrace: type: class java.lang.NullPointerException
03 May 09:51:56 JSPHelper WARN - Error page reached! 
java.lang.NullPointerException
java.lang.NullPointerException
at edu.stanford.muse.ner.NER.getNameOffsets(NER.java:203)
at edu.stanford.muse.ner.NER.retainOnlyNames(NER.java:515)
at edu.stanford.muse.index.Archive.replaceDescriptionWithNames(Archive.java:810)
at edu.stanford.muse.index.Archive.export(Archive.java:874)
at org.apache.jsp.export_002dcomplete_002dprocessing_jsp._jspService(export_002dcomplete_002dprocessing_jsp.java:310)
at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:438)
at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:396)
at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:340)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
at edu.stanford.muse.webapp.LoggingFilter.doFilter(LoggingFilter.java:26)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518)
at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1096)
at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:674)
at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500)
at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1456)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
at java.lang.Thread.run(Unknown Source)

03 May 10:11:51 JSPHelper INFO - NEW Request[user@0:0:0:0:0:0:0:1]: http://localhost:9099/epadd/debug link: http://localhost:9099/epadd/debug?

**Comment by peterchanws** [comment]
Version Apr 26
works fine
